name: Hprofile-Actions
on: workflow_dispatch
env:
  aws_region: ap-south-1
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing Workflow
        run: echo "Workflow executed successfully"

      - name: Checkout the Git Code from the repo
        uses: actions/checkout@v5

      - name: Maven Test Code
        run: mvn test

      - name: Maven run CheckStyle command to generate files of QA
        run: mvn checkstyle:checkstyle

        #Setup Java in the Workflow of Version 17
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Setup Sonar
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_CLOUD_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJ_KEY }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportPaths=target/surefire-reports/
          -Dsonar.jacoco.reportPaths=target/jacoco.exec
          -Dsonar.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest
  
  BUILDANDTEST:
    needs: Testing
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Edit the Username and Password in the application.properties file
        run: |
          sed -i "s|^jdbc.username.*$|jdbc.username=${{ secrets.RDS_USER }}|" src/main/resources/application.properties
          sed -i "s|^jdbc.password.*$|jdbc.password=${{ secrets.RDS_PASSWORD }}|" src/main/resources/application.properties
          sed -i "s|db01|${{ secrets.RDS_ENDPOINT }}|" src/main/resources/application.properties

      - name: Build Docker File
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.ECR_REGISTRY }}
          repo: vprofile-app
          region: ${{ env.aws_region }}
          tag: latest, ${{ github.run_number}}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./

