name: Hprofile-Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing Workflow
        run: echo "Workflow executed successfully"

      - name: Checkout the Git Code from the repo
        uses: actions/checkout@v5

      - name: Maven Test Code
        run: mvn test

      - name: Maven run CheckStyle command to generate files of QA
        run: mvn checkstyle:checkstyle

        #Setup Java in the Workflow of Version 17
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Setup Sonar
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_CLOUD_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJ_KEY }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportPaths=target/surefire-reports/
          -Dsonar.jacoco.reportPaths=target/jacoco.exec
          -Dsonar.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest


        
