name: Hprofile-Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing Workflow
        run: echo "Workflow executed successfully"

      - name: Checkout the Git Code from the repo
        uses: actions/checkout@v5

      - name: Maven Test Code
        run: mvn test

      - name: Maven Build and Compile the code
        run: mvn clean compile

      - name: Maven run CheckStyle command to generate files of QA
        run: mvn checkstyle:checkstyle

      - name: Setup Sonar
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_CLOUD_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJ_KEY }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportPaths=target/surefire-reports/
          -Dsonar.jacoco.reportPaths=target/jacoco.exec
          -Dsonar.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/

      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          pollingTimeoutSec: 600
          args:
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_CLOUD_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJ_KEY }}
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_CLOUD_URL }}
        
